[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
backend = "H2QcxTVK9sWKBTVE6sg8uJ7KxfDcB5zwDQ92E7ED1gzW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/asimnecip/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
