[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rust_backend = "AwCDoyQvn8H9oszX7EkzVhM1L6DFu6QCE1vqPM34gbtG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/asimnecip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
